import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex(ETableNames.course).del();

    // Inserts seed entries
    await knex(ETableNames.course).insert(coursesData);
}

const coursesData = [
    { name: "Javascript" },
    { name: "Java" },
    { name: "Rust" },
    { name: "Ruby" },
    { name: "R" },
    { name: "C" },
    { name: "C++" },
    { name: "C#" },
    { name: "HTML" },
    { name: "CSS" },
    { name: "React" },
    { name: "Angular" },
    { name: "Vue" },
    { name: "Svelte" },
    { name: "Typescript" },
    { name: "Coffescript" },
    { name: "Delphi" },
    { name: "Pascal" },
    { name: "Turbo Pascal" },
    { name: "VB" },
    { name: "F#" },
    { name: ".NET" },
    { name: "Python" },
    { name: "Ada" },
    { name: "Bash" },
    { name: "Sh" },
    { name: "B" },
    { name: "D" },
    { name: "Bootstrap" },
    { name: "Material" },
    { name: "VB6" },
    { name: "Next.js" },
    { name: "Express.js" },
    { name: "Deno" },
    { name: "Bun" },
    { name: "Jocelyn Norris" },
    { name: "Francesca Kemp" },
    { name: "Orlando Petersen" },
    { name: "Jerome O'connor" },
    { name: "Rina Hood" },
    { name: "Reece Mercer" },
    { name: "Colby Hicks" },
    { name: "Lars Patrick" },
    { name: "Phillip Waller" },
    { name: "Josiah Blair" },
    { name: "Haley Farrell" },
    { name: "Shelby Dotson" },
    { name: "Daphne Graham" },
    { name: "Wynter Hinton" },
    { name: "Brent Calderon" },
    { name: "Jena Preston" },
    { name: "Mollie Elliott" },
    { name: "Alvin Sanchez" },
    { name: "Shana Bird" },
    { name: "Miranda Ortega" },
    { name: "Lucas Aguilar" },
    { name: "Ori Mendoza" },
    { name: "Alika Travis" },
    { name: "Palmer Whitley" },
    { name: "Diana Dennis" },
    { name: "Iona Dale" },
    { name: "Avram Harding" },
    { name: "Noel Schroeder" },
    { name: "Rafael Hurley" },
    { name: "Carly Bonner" },
    { name: "Suki Jacobs" },
    { name: "Myles Mcguire" },
    { name: "Barclay Meyer" },
    { name: "Odysseus Hoffman" },
    { name: "Haley Branch" },
    { name: "Audrey Wall" },
    { name: "Abel Lang" },
    { name: "Winter Stanton" },
    { name: "Donovan Jimenez" },
    { name: "Mannix Sharp" },
    { name: "Kaitlin Weber" },
    { name: "Dominique Hanson" },
    { name: "Flavia Rosa" },
    { name: "Daryl Kline" },
    { name: "Hedda Hatfield" },
    { name: "Avye Osborn" },
    { name: "Oscar Robinson" },
    { name: "Levi Kim" },
    { name: "Karyn Mcguire" },
    { name: "Joan Gardner" },
    { name: "Jaquelyn Mcknight" },
    { name: "Gavin Paul" },
    { name: "Nora Sheppard" },
    { name: "Adena Atkinson" },
    { name: "Francesca Fernandez" },
    { name: "Noel Ramsey" },
    { name: "Daria Schneider" },
    { name: "Myles Osborn" },
    { name: "Aiko Caldwell" },
    { name: "Cullen Decker" },
    { name: "Xander Browning" },
    { name: "Shellie Parker" },
    { name: "Brandon Livingston" },
    { name: "Cain Farley" },
    { name: "Byron Hardin" },
    { name: "Lenore Yang" },
    { name: "Tana Franks" },
    { name: "Declan Cox" },
    { name: "Guy Sanford" },
    { name: "Malcolm Pollard" },
    { name: "Damon Campbell" },
    { name: "Kay Mayo" },
    { name: "Rhiannon Russell" },
    { name: "Margaret Lee" },
    { name: "Inez Conway" },
    { name: "Wendy Frazier" },
    { name: "Branden Nielsen" },
    { name: "Carolyn Parsons" },
    { name: "Charissa Schroeder" },
    { name: "Anastasia Norris" },
    { name: "Neil Hayes" },
    { name: "Clinton Goff" },
    { name: "Lysandra O'Neill" },
    { name: "Rana Bray" },
    { name: "Steven Waller" },
    { name: "Byron Prince" },
    { name: "Buffy Barry" },
    { name: "Phoebe Prince" },
    { name: "Amy Jacobson" },
    { name: "Drake Marks" },
    { name: "Craig Sanchez" },
    { name: "Violet Gordon" },
    { name: "Gavin Mullins" },
    { name: "Winter Rollins" },
    { name: "Colt Hunt" },
    { name: "Anthony Clay" },
    { name: "Halee Summers" },
    { name: "Adrian Wilcox" },
    { name: "Jacqueline Brady" },
    { name: "Tate Mckee" },
    { name: "Ariana Rosa" },
    { name: "Hoyt Hopkins" },
    { name: "Vera Holman" },
    { name: "Kelsie Lester" },
    { name: "Rafael Jarvis" },
    { name: "Helen Murray" },
    { name: "Curran Anthony" },
    { name: "Uriel Huffman" },
    { name: "Xena Knowles" },
    { name: "Carlos Parsons" },
    { name: "Fredericka Velez" },
    { name: "Isabelle Santos" },
    { name: "Desiree Parrish" },
    { name: "Serena Townsend" },
    { name: "Deirdre Gill" },
    { name: "Clayton Carroll" },
    { name: "Hashim Mays" },
    { name: "Shafira England" },
    { name: "Barclay Hart" },
    { name: "Chase Shields" },
    { name: "Connor Ford" },
    { name: "Bruno Gregory" },
    { name: "Denton Calderon" },
    { name: "Nero Eaton" },
    { name: "Alexa Macdonald" },
    { name: "Rogan Gates" },
    { name: "Harriet Copeland" },
    { name: "Odysseus Snyder" },
    { name: "Marny Russo" },
    { name: "Lilah Morris" },
    { name: "Zeph Mathis" },
    { name: "Malik Fisher" },
    { name: "Dieter King" },
    { name: "Hashim Garrett" },
    { name: "Ryder Price" },
    { name: "Hadassah Holloway" },
    { name: "Indigo Steele" },
    { name: "Georgia Downs" },
    { name: "Jared Davidson" },
    { name: "Branden Decker" },
    { name: "Audra Mejia" },
    { name: "Barclay Stephenson" },
    { name: "Jeremy Howard" },
    { name: "Dai Clayton" },
    { name: "Hanna Head" },
    { name: "Nash Bradford" },
    { name: "Finn Henry" },
    { name: "Kaseem Hammond" },
    { name: "Felicia Cooper" },
    { name: "Kieran Beck" },
    { name: "Channing Finley" },
    { name: "Dominique Fisher" },
    { name: "Tate Duran" },
    { name: "Janna Fleming" },
    { name: "Sydnee Whitley" },
    { name: "Emi Gonzales" },
    { name: "Evan Thomas" },
    { name: "Bryar Humphrey" },
    { name: "Graiden Richardson" },
    { name: "Keiko Johnson" },
    { name: "Ayanna Hess" },
    { name: "Josephine Short" },
    { name: "Jermaine Woods" },
    { name: "Doris Hewitt" },
    { name: "Judith Webster" },
];
